name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Cache .gradle
        uses: actions/cache@v3
        with:
          path: $USER_HOME/.gradle
          key: ${{ runner.os }}-${{ hashFiles('*.gradle') }}-gradle-user-home

      - name: Build
        env:
          GH_REF: ${{ github.ref }}
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/js/packages/agent-bot

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd build/js/packages/agent-bot
          echo "registry=https://npm.pkg.github.com/xtexChooser/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          npm get
          npm publish --access=public --no-workspace
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u xtexChooser --password-stdin
          docker build -t agent-bot .
          docker push ghcr.io/xtexChooser/agent-bot:latest
