name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Cache .gradle
        uses: actions/cache@v3
        with:
          path: $USER_HOME/.gradle
          key: ${{ runner.os }}-${{ hashFiles('*.gradle') }}-gradle-user-home

      - name: Build
        env:
          GH_REF: ${{ github.ref }}
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kt-js
          path: build/js/packages/agent-bot

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker login ghcr.io -u xtexChooser --password ${{ secrets.GITHUB_TOKEN }}
          docker build -t ghcr.io/xtexchooser/agent-bot .
          docker images
          docker push ghcr.io/xtexchooser/agent-bot:latest
